#version 460 core
layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0, rgba32f) uniform writeonly image2D displacementTexture;
uniform sampler2D spatialTextureA;
uniform sampler2D spatialTextureB;
uniform uint resolution;
uniform float heightScale;
uniform float horizontalScale;

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    if (coord.x >= int(resolution) || coord.y >= int(resolution)) {
        return;
    }

    vec4 spatialA = texelFetch(spatialTextureA, coord, 0);
    vec2 spatialB = texelFetch(spatialTextureB, coord, 0).xy;
    vec3 displacement = vec3(
        spatialA.x * horizontalScale,
        spatialA.z * heightScale,
        spatialB.x * horizontalScale
    );
    imageStore(displacementTexture, coord, vec4(displacement, 1.0));
}
